### ISSUE TITLE
decryptbytes: procdecryptdata: The parameter is incorrect when consuming using api keys in the command

### ISSUE THREAD

**Issue by natalia-ramos-bzy** [confluentinc/cli#2412] opened 2023-11-10 09:45 UTC
There's an error when consuming a topic using api keys in the command
```
confluent kafka topic consume <topicName> --from-beginning --schema-registry-api-key <srApiKey> --schema-registry-api-secret <srApiSecret> --api-key <kafkaApiKey> --api-secret <kafkaApiSecret> --environment <env> --cluster <cluster>
Error: failed to create consumer: decryptbytes: procdecryptdata: The parameter is incorrect.
```

```
confluent - Confluent CLI

Version:     v3.40.0
Git Ref:     299e722ef
Build Date:  2023-11-02T23:32:56Z
Go Version:  go1.21.0 X:boringcrypto (windows/amd64)
Development: false
```

**Comment by MuweiHe** [comment] 2023-11-13 23:20
Hi, we received a similar issue where it was fixed by creating a new pair of api-key. You may want to try that and see if it can resolve the issue for now. I'll continue investigate. The issue is probably in the process of encrypting/decrypting credentials using windows dpapi.

**Comment by MuweiHe** [comment] 2023-11-13 23:26
There's very limited info we could get on this issue. I will do a release this week to add more traces/logs in this command, and can you provide me the output / traces you see using the newer version so I can debug further? Will comment here when the new version is out

**Comment by MuweiHe** [comment] 2023-11-30 18:54
hi @natalia-ramos-bzy are you still seeing this issue? You may want to update to latest cli release, and run the same command with `--unsafe-trace`. Please provide me without the logs output and that will help us investigate. Thanks!

**Closed** 2024-12-09 19:50 UTC
Labels: bug
